username: retronexus
shell: /bin/bash
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - htop
  - neofetch
  - rsync
  - software-properties-common
  - speedtest-cli
  - tmux  
  - unattended-upgrades
  - vim
  - resolvconf
  - wireguard