# Create docker folder
- name: Create Docker folders
  ansible.builtin.file:
    path: docker
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes

- name: Create Docker folder for compose files
  ansible.builtin.file:
    path: /src/docker
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes

# Create wireguard config folder
- name: Create Docker folders
  ansible.builtin.file:
    path: /src/docker/wireguard-server/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes

# Create gluetun config folder
- name: Create gluetun folders
  ansible.builtin.file:
    path: /src/docker/gluetun/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes

# Create radarr config folder
- name: Create radarr folders
  ansible.builtin.file:
    path: /src/docker/radarr/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes

# Create sonarr config folder
- name: Create sonarr folders
  ansible.builtin.file:
    path: /src/docker/sonarr/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes    

# Create prowlarr config folder
- name: Create prowlarr folders
  ansible.builtin.file:
    path: /src/docker/prowlarr/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes        

# Create qbittorrent config folder
- name: Create qbittorrent folders
  ansible.builtin.file:
    path: /src/docker/qbittorrent/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: 0775
    recurse: yes        