- name: ENSURE ALL GROUPS ARE CREATED
  group:
    name: "{{ item }}"
  loop:
    - docker
    - samba
    - "{{ username }}"

- name: ENSURE NON-ROOT USER IS CREATED
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
      - users
    append: yes
    shell: "{{ shell }}"
    update_password: on_create

- name: ENABLE PASSWORDLESS SUDO FOR "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: SUPPRESS LOGIN MESSAGE (HUSHLOGIN)
  file:
    path: /home/{{ username }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch
