# User
username: retronexus

# Shell config
shell: /bin/bash

# Packages to be installed
base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - htop
  - neofetch
  - rsync
  - software-properties-common
  - speedtest-cli
  - tmux  
  - unattended-upgrades
  - vim
  - resolvconf
  - wireguard

# SSH configuration
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
