# Create docker folder
- name: CREATE MAIN CONFIG FOLDER
  become: true
  file:
    path: /src/docker-config
    state: directory
    owner: retronexus
    group: retronexus
    mode: '0775'
    recurse: yes                     

# Create docker config folders
- name: CREATE DOCKER CONTAINER CONFIG FOLDERS
  become: true
  file:
    path: /src/docker-config/{{item}}/config
    state: directory
    owner: retronexus
    group: retronexus
    mode: '0775'
    recurse: yes
  with_items: "{{docker_config_dirs}}"